<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LIVE_chapters</name>
   <tag></tag>
   <elementGuidId>8ce04745-5914-4f38-a78f-970b923e45ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='41622060']/div[7]/div[3]/div/div[3]/div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.chapters</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chapters</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;41622060&quot;)/div[@class=&quot;vp-controls-wrapper&quot;]/div[@class=&quot;vp-controls&quot;]/div[@class=&quot;play-bar rounded-box&quot;]/div[@class=&quot;vp-progress&quot;]/div[@class=&quot;chapters&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='41622060']/div[7]/div[3]/div/div[3]/div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]</value>
   </webElementXpaths>
</WebElementEntity>
